### ISSUE TITLE
Compile fails on erlang 18

### ISSUE THREAD

**Issue by jeanparpaillon** [aol/erlgraph#1]
Compiling with erlang 18 produces:
ERROR: OTP release 18 does not match required regex 17
ERROR: compile failed while processing /home/jean/BA_Projets/git/erlgraph/deps/cowlib: rebar_abort
Makefile:7: recipe for target 'compile' failed
make: **\* [compile] Error 1

**Comment by byaruhaf** [comment]
@jeanparpaillon 

Update the rebar.config and change the line
from
    {require_otp_vsn, "17"}.
to
    {require_otp_vsn, "17|18"}.

**Comment by philip-clarke** [comment]
thanks for the pull request.  merged now

**Comment by jeanparpaillon** [comment]
Works now !
