### ISSUE TITLE
unable to pull deps

### ISSUE THREAD

**Issue by stuart-thackray** [aol/erlgraph#4]
```
{jiffy, ".*", {git, "git@github.com:davisp/jiffy.git", {tag, "0.9.0"}}}
```

When pulling the dependency get 
Pulling jiffy from {git,"git@github.com:davisp/jiffy.git",{tag,"0.9.0"}}
Cloning into 'jiffy'...
ssh_askpass: exec(/usr/X11R6/bin/ssh-askpass): No such file or directory
Host key verification failed.
fatal: Could not read from remote repository.

Can be fixed by changing the line in rebar.config to the below.
    {jiffy, ".*", {git, "https://github.com/davisp/jiffy.git", {tag, "0.9.0"}}}

**Comment by danielpacak** [comment]
+1

**Comment by philip-clarke** [comment]
Thanks Stuart !
Pull request is merged
